### ISSUE TITLE
Add filter to processed fields

### ISSUE THREAD

**Issue by eSaner** [wpcorner/footnotes-made-easy#1]
Thanks for taking over this plugin! Would love to see a filter added to line 161 of footnotes-made-easy.php that would allow the fields processed by the plugin to be modified (e.g.  add acf_the_content).

**Comment by manuell18** [comment]
I have added this code to the plugin, you should have changes reflected soon.

**Comment by manuell18** [comment]
you can modify which fields are processed by adding a filter in your theme's functions.php file or a custom plugin. Here's an example:

function modify_footnotes_made_easy_fields($fields) {
    $fields[ ] = 'acf_the_content';  // Adding an ACF field to be processed
    return $fields;
}
add_filter('footnotes_made_easy_fields', 'modify_footnotes_made_easy_fields');

**Comment by eSaner** [comment]
Fantastic. Thank you!
