### ISSUE TITLE
How can I style the qTip / tooltip box?

### ISSUE THREAD

**Issue by HaggenKennedy** [wpcorner/footnotes-made-easy#16]
Hi!

What's the procedure to correctly change the style of the qtip (the little tooltip box) into which the footnote message appears? I read somewhere (I think in the readme file, but I'm not sure?) that you could change styles by editing the css file? I can't remember whether that was the "css" or "the css file". I logged into my cPanel, accessed my wp content folder, then went to the footnote plugin, then the CSS folder, to the **tooltips.css** file. I saw this inside it:

.ui-widget-content {
border: 1px solid #dddddd;
**background: #eeeeee;**
color: #333333;
}

I figured the **#eeeeee** referred to the box's background color, so, just as a test, I selected the tooltips.css file, then clicked "Edit" on cPanel, and I changed that value to "#ffffff" to see if the background would change to white. But nothing happened, it's still gray. Could you tell me what to do? Is that not the right place to configure the qtip box style? Should I use that CSS command in the "Custom CSS" section of my website instead (rather than change the tooltips.css file)? Because changing the tooltips.css file doesn't seem to do anything. I don't even know if it's the right file to alter. And I don't want to poke too much or change anything too much for fear it might break my website. These things are so finicky! One wrong line of code, or a conflict somewhere, and all goes kablooey. Can you help?

Thank you so much in advance.

**Comment by lumumbapl** [comment]
Hello @HaggenKennedy 

I apologize for taking long to respond to this issue. 

Now, you were on the right path, except, the CSS selector was wrong. You almost got it right.😅

The correct class selector is `.ui-tooltip`

In the demo below, I set the background color to `black` and the text color to `white`

![Tooltips](https://github.com/user-attachments/assets/6863f144-cef0-40da-b48e-0e5534af19e9)

Here is the complete CSS used to achieve the above:

```
/* Style the tooltip */
.ui-tooltip {
background: #000;
color: #fff;
}
 ```

That's it.

Try it and let me know how it goes. 

Regards.

Patrick.

**Comment by HaggenKennedy** [comment]
Hi, Patrick, no worries. Sorry for taking so long to get back to you, too.

I tried changing the CSS on the ".ui-tooltip" selector in the "tooltips.css" file, but it didn't work. I wondered if that's because I needed to change the same settings inside the "tooltips.min.css" file -- I don't know what the difference is between them, but I thought perhaps one might be influencing or conflicting the other.

But I just didn't feel so comfortable messing around with those files, and I thought I should just try to use the general CSS area instead (the one in the "Additional CSS" customization area, in Wordpress/DIVI). Every time you try to edit a file using cPanel, they give you all those warnings that the world will end if you screw up, and my anxiety can't handle that. 🤣 So I just used the Additional CSS customization area, and lo and behold!, it worked. So no need to mess with those CSS files, I could just customize the qtip any way I wanted in the CSS area of my website (I even applied some soft gradient to the tooltip box, it looks rather nice).

In other words, the ".ui-tooltip" selector was the decisive factor. With it you can do whatever you want in the customization area, the same way I did with the footnotes themselves. So, it's all working just fine now.

If I were to suggest an addition, it would probably be an extra field on the main panel, where you have "Identifier, symbol, superscript" etc., so users can set the **size** of the superscript (since it's 100% by default), and perhaps a way to style the qtip? Not sure how that would work, maybe some CSS field, or maybe some color boxes where you could set the color and the opacity, and the border and the shadow. Or maybe that's just too complicated, in which case there could be either a box where you could input some CSS, or perhaps even something as simple as some information stating:

1. Selector for qtip styling: ".ui-tooltip"
2. Selector for superscript styling: ".footnote-link"
3. Selector for footnote back-link styling: ".footnote-back-link"
4. Selector for the footnotes at the bottom of the page: "X"
5. Etc.

Something like that. I think actual devs, people who are familiar with programming/scripting, can find that info very easily, but for users like me who aren't from the tech world, and/or don't work with this for a living, it would be very beneficial. Just a thought.

At any rate, thank you so much again, Patrick. I really appreciate all the help, I know you've put a lot of time into this -- time that you could use to be with your family. So, Thank you so much, for everything!

**Comment by lumumbapl** [comment]
Hello @HaggenKennedy 

Thank you for the kind words. And thank you for the suggestions.

For now, I'm going to add the information below to the plugin's documentation page. I believe it would be helpful to most users.

Once again, thank you.

Patrick.
