### ISSUE TITLE
PHP 8.2 Deprecated Creation of dynamic property

### ISSUE THREAD

**Issue by jcvignoli** [wpcorner/footnotes-made-easy#8]
Hi,
Just updated to latest footnotes made easy from 2.5 version. A longstanding PHP 8.2 bug is back again.

I get the message

`Deprecated: Creation of dynamic property swas_wp_footnotes::$styles is deprecated in wp-content/plugins/footnotes-made-easy/footnotes-made-easy.php on line 54`

on any admin page.

Thanks for looking into it!

**Comment by manuell18** [comment]
Thank you for raising this up. I will be declaring the $styles property in the class. That should allow compatibility with newer versions.

**Comment by lumumbapl** [comment]
This fix will be available in the next release. 

Thanks, @manuell18

**Comment by jcvignoli** [comment]
Hi there,
Is there any ETA for the next release? Waiting since May...

**Comment by pmochine** [comment]
Friendly reminder <3

**Comment by Amenel** [comment]
I have upgraded to release 3.0.5 from November 2, and unfortunately, I still see this deprecation notice on my development environment.

I've also taken a look a minute ago at the code and indeed, there's no `private $styles` in the class prior to line 54. It seems like the changes in merge request #12 has been overwritten as I can see that the declaration was added in line 45.

Could you please redo the release? I guess we've been waiting for this for a few months and release 3.0.5 has missed the mark on being PHP 8.2 compatible. In the meantime, I'll have to keep this extension disabled.

Many thanks in advance.

**Comment by lumumbapl** [comment]
The issue is now resolved in version 3.0.6.
